platform :ios,’7.0’
pod 'SDWebImage', '~> 3.7.3'
pod 'AFNetworking', '~> 2.1.0'
pod 'MJRefresh', '~> 3.0.7'
pod 'Toast', '~> 3.0'
pod 'BmobSDK'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'MOBFoundation_IDFA'
pod 'SMSSDK'
pod 'IQKeyboardManager', '~> 3.3.4'